### PR TITLE
Docker image basics

### PR DESCRIPTION
**Pull request by merlinschumacher**
Hi,

I've created a Dockerfile and docker-compose.yml for linguard. The docker-compose.yml expects the image to be build locally. At a later time I could provide an actions workflow that builds and pushes the image to GHCR.

### CODE REVIEW

**Comment by joseantmazonsb** [comment]
Cool! This will definitely save me some time. However, I'm changing the project's workflow, so that the `main` branch will only be used to release new versions of Linguard. A PR targeting the `dev` branch would be the right thing to do for now on, and I would appreciate if you did so. I will specify this kind of things in a `CONTRIBUTING.md` file as soon as possible 😅

**Comment by joseantmazonsb** [comment]
Closing due to inactivity. Docker images have already been included in release 1.0.0

**Comment by merlinschumacher** [comment]
Hey @joseantmazonsb! Sorry for being inactive and not reacting to your request. Either way: Thanks for your work!

**Comment by joseantmazonsb** [comment]
> Hey @joseantmazonsb! Sorry for being inactive and not reacting to your request. Either way: Thanks for your work!

Don't worry and remember that you can still contribute anytime!

**Pull request closed without merging**
